-- =====================================================
-- SQL Скрипт за Supabase:
-- 1. Таблица 'invites' (за отговорите от формата)
-- 2. Таблица 'visitor_logs' (за проследяване кой влиза/излиза, IP, устройство, времетраене)
-- 3. Активиране на Supabase Realtime
-- Копирай и постави в Supabase -> SQL Editor -> Run
-- =====================================================

-- -----------------------------------------------------
-- 1. ТАБЛИЦА 'invites'
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.invites (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  phone TEXT NOT NULL,
  place TEXT NOT NULL,
  date TEXT NOT NULL,
  time TEXT NOT NULL,
  special_wish TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.invites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert invites" ON public.invites
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow service_role all invites" ON public.invites
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------
-- 2. ТАБЛИЦА 'visitor_logs' (Кой влиза и излиза)
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.visitor_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id TEXT NOT NULL UNIQUE,
  name TEXT,
  ip TEXT,
  device TEXT,
  browser TEXT,
  os TEXT,
  user_agent TEXT,
  current_page TEXT,
  referrer TEXT,
  entered_at TIMESTAMPTZ DEFAULT NOW(),
  left_at TIMESTAMPTZ DEFAULT NOW(),
  duration_seconds INTEGER DEFAULT 0,
  is_online BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_visitor_logs_session ON public.visitor_logs (session_id);
CREATE INDEX IF NOT EXISTS idx_visitor_logs_entered ON public.visitor_logs (entered_at DESC);

ALTER TABLE public.visitor_logs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert visitor_logs" ON public.visitor_logs
  FOR INSERT TO anon, authenticated WITH CHECK (true);

CREATE POLICY "Allow anon update visitor_logs" ON public.visitor_logs
  FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Allow service_role all visitor_logs" ON public.visitor_logs
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- -----------------------------------------------------
-- 3. АКТИВИРАНЕ НА SUPABASE REALTIME
-- (Позволява live известия в реално време при влизане и излизане)
-- -----------------------------------------------------
DO $$
BEGIN
  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.invites;
  EXCEPTION WHEN duplicate_object THEN
    -- Table already in publication
  END;

  BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.visitor_logs;
  EXCEPTION WHEN duplicate_object THEN
    -- Table already in publication
  END;
END $$;
